- hosts: vagrant
  user: vagrant
  gather_facts: no
  tasks:
    - name: git
      yum: name=git update_cache=yes state=latest
      become: true
      become_method: sudo
  roles:
    - role: nginx
    - role: erlang
    - role: elixir
    - role: phoenix
    - role: nodejs
    - role: postgres
