- hosts: vagrant
  become: yes
  become_user: root
  user: vagrant
  tasks:
    - name: git
      yum: name=git update_cache=yes state=latest
  roles:
    - role: nginx
    - role: erlang
    - role: elixir
    - role: phoenix
    - role: nodejs
