- name: install required packages
  yum: pkg={{item}} state=installed
  with_items:
    - gcc
    - glibc-devel
    - make
    - ncurses-devel
    - openssl-devel
    - autoconf
- name: check whether the source file exists, or not
  command: ls -l /var/tmp/otp_src_18.0.tar.gz
  ignore_errors: yes
  register: arleady_exists
- name: get source
  get_url: url=http://www.erlang.org/download/otp_src_18.0.tar.gz dest=/var/tmp/
  when: arleady_exists|failed
- name: unzip source
  command: chdir=/var/tmp/ tar zxvf otp_src_18.0.tar.gz
  when: arleady_exists|failed
- name: check whether erlang had been installed, or not
  command: which erl
  ignore_errors: yes
  register: arleady_installed
- name: move source files
  command: cp /var/tmp/otp_src_18.0 /usr/local/src/otp_src_18.0
  when: arleady_installed == "/usr/local/bin/erl"
- name: configure erlang
  command: chdir=/usr/local/src/otp_src_18.0 ./configure
  when: arleady_installed == "/usr/local/bin/erl"
- name: make elixir
  command: chdir=/usr/local/src/otp_src_18.0 make
  when: arleady_installed == "/usr/local/bin/erl"
- name: configure erlang
  command: chdir=/usr/local/src/otp_src_18.0 make install
  when: arleady_installed == "/usr/local/bin/erl"
