- name: add epel repo
  yum: name=http://ftp.iij.ad.jp/pub/linux/fedora/epel/6/x86_64/epel-release-6-8.noarch.rpm state=installed
- name: install node.js
  yum: name=nodejs enablerepo=epel state=latest
