- name: install hex
  command: /home/vagrant/bin/mix local.hex && Y
- name: download elixir package
  command: /home/vagrant/bin/mix archive.install https://github.com/phoenixframework/phoenix/releases/download/v1.0.3/phoenix_new-1.0.3.ez
