- name: install hex
  command: mix local.hex && Y
  args:
    chdir: /home/vagrant
  ignore_errors: yes
- name: download elixir package
  command: mix archive.install https://github.com/phoenixframework/phoenix/releases/download/v1.0.3/phoenix_new-1.0.3.ez
  args:
    chdir: /home/vagrant
  ignore_errors: yes

- name: install required npm-packages
  command: npm install
  args:
    chdir: /home/vagrant
  ignore_errors: yes
